"use strict";
let str = "文字列";
console.log(str);
let num = 1;
console.log(num);
let bool = true;
console.log(bool);
let str2 = "moji";
str2 = "aaa";
console.log(str2);
// console.log(str, num, bool, func(), obj);
